#!/usr/bin/env python3
"""
Pulls the Qur'an text for every surah in data/surahs.js and writes data/verses.js.

For each verse it stores:
  t   the Uthmani Arabic text of the whole verse
  e   the English translation (Saheeh International by default)
  w   the word-by-word list: [arabic, english, transliteration] per word

Run it after adding a surah:   python3 fetch_verses.py
It skips surahs that are already in data/verses.js unless you pass --all.

Source: the Quran.com API (api.quran.com/api/v4), which serves the
Quranic Arabic Corpus word-by-word data.
"""

import json, re, sys, time, urllib.request, urllib.error, os

HERE        = os.path.dirname(os.path.abspath(__file__))
SURAHS_JS   = os.path.join(HERE, "data", "surahs.js")
VERSES_JS   = os.path.join(HERE, "data", "verses.js")
# Which English translation appears under each verse. Change the number and
# re-run with --all to swap it. The API's English options are:
#   20  Saheeh International        85  M.A.S. Abdel Haleem
#   84  Mufti Taqi Usmani           19  Pickthall
#   22  Yusuf Ali                   95  Maududi (Tafhim)
#   203 Hilali & Khan              149  Bridges
# (The Clear Quran / Khattab is not offered by this API — it isn't openly licensed.)
TRANSLATION = 20
API         = ("https://api.quran.com/api/v4/verses/by_chapter/{n}"
               "?words=true&word_fields=text_uthmani&fields=text_uthmani"
               "&translations={t}&per_page=300&language=en")

SUP_RE = re.compile(r"<sup\\b[^>]*>.*?</sup>", re.S)   # footnote markers, number and all
# Qur'anic recitation marks (waqf signs, small letters). They are pause and
# tajwid aids, not part of a word's spelling, and the Amiri webfont has no
# glyphs for several of them \u2014 which breaks the letter joins on screen. The
# dagger alef (U+0670) is a real long \u0101 and is deliberately NOT in this set.
ANNOT_RE = re.compile("[\u06D6-\u06ED\u08F0-\u08FF]")
TAG_RE = re.compile(r"<[^>]+>")                       # any other stray markup


def ar(s):
    return ANNOT_RE.sub("", s or "").strip()


def surah_numbers():
    src = open(SURAHS_JS, encoding="utf-8").read()
    return sorted({int(m) for m in re.findall(r"\bnum:\s*(\d+)", src)})


def existing():
    if not os.path.exists(VERSES_JS):
        return {}
    src = open(VERSES_JS, encoding="utf-8").read()
    m = re.search(r"const VERSES\s*=\s*(\{.*\});?\s*$", src, re.S)
    return json.loads(m.group(1)) if m else {}


def get(url, tries=4):
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "kalimah/1.0"})
            with urllib.request.urlopen(req, timeout=45) as r:
                return json.loads(r.read().decode("utf-8"))
        except Exception as e:
            if attempt == tries - 1:
                raise
            print("    retry (%s)" % e)
            time.sleep(2 + attempt * 3)


def clean_en(s):
    s = SUP_RE.sub("", s or "")
    s = TAG_RE.sub("", s)
    s = re.sub(r"\s+", " ", s)
    return re.sub(r"\s+([,.;:!?])", r"\1", s).strip()


def fetch(num):
    data = get(API.format(n=num, t=TRANSLATION))
    if not (data["verses"][0].get("translations") or [{}])[0].get("text"):
        raise SystemExit("Translation %s returned nothing — pick another id from the "
                         "list at the top of this file." % TRANSLATION)
    out = {}
    for v in data["verses"]:
        key = v["verse_key"].split(":")[1]
        tr  = v.get("translations") or [{}]
        words = []
        for w in v.get("words", []):
            if w.get("char_type_name") != "word":
                continue                      # skip the end-of-verse number glyph
            words.append([
                ar(w.get("text_uthmani")),
                clean_en((w.get("translation") or {}).get("text")),
                ((w.get("transliteration") or {}).get("text") or "").strip(),
            ])
        out[key] = {
            "t": ar(v.get("text_uthmani")),
            "e": clean_en(tr[0].get("text")),
            "w": words,
        }
    return out


def main():
    refetch = "--all" in sys.argv
    store = {} if refetch else existing()
    nums = surah_numbers()

    for n in nums:
        if str(n) in store:
            print("  %3d  already have it" % n)
            continue
        print("  %3d  fetching..." % n, flush=True)
        store[str(n)] = fetch(n)
        time.sleep(0.4)                        # be polite to the API

    for k in list(store):
        if int(k) not in nums:
            del store[k]                       # surah no longer in the site

    os.makedirs(os.path.dirname(VERSES_JS), exist_ok=True)
    body = json.dumps(store, ensure_ascii=False, separators=(",", ":"))
    with open(VERSES_JS, "w", encoding="utf-8") as f:
        f.write("/* Generated by fetch_verses.py — do not edit by hand.\n"
                "   Qur'an text and word-by-word data from the Quran.com API.\n"
                "   Translation: Saheeh International.                        */\n")
        f.write("const VERSES = " + body + ";\n")

    v = sum(len(s) for s in store.values())
    w = sum(len(x["w"]) for s in store.values() for x in s.values())
    print("\n  %d surahs, %d verses, %d words  ->  data/verses.js  (%.0f KB)"
          % (len(store), v, w, os.path.getsize(VERSES_JS) / 1024))


if __name__ == "__main__":
    main()
